# Generated by Django 4.1.7 on 2023-04-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customaccount', '0002_studentaccount_fundationstaffaccount'),
        ('fundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundation',
            name='type',
            field=models.CharField(choices=[('UNIVERSITY', 'University'), ('SCHOOL', 'School')], default='SCHOOL', max_length=10),
        ),
        migrations.AlterField(
            model_name='fundation',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='staffFundation', to='customaccount.fundationstaffaccount'),
        ),
        migrations.AlterField(
            model_name='fundation',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='studentFundation', to='customaccount.studentaccount'),
        ),
    ]
