# Generated by Django 4.1.7 on 2023-04-12 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundation', '0002_fundation_type_alter_fundation_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundation',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
