# Generated by Django 4.1.7 on 2023-04-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text=None, max_length=50, unique=True)),
                ('email', models.EmailField(help_text=None, max_length=254, null=True, unique=True, verbose_name=' الايميل  ')),
                ('first_name', models.CharField(default='', help_text=None, max_length=30, verbose_name=' الاسم الاول  ')),
                ('last_name', models.CharField(default='', help_text=None, max_length=30, verbose_name=' الاسم الاخير  ')),
                ('is_admin', models.BooleanField(default=False, help_text=None, verbose_name=' مسؤل موقع  ')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='  مدير ')),
                ('is_active', models.BooleanField(default=True, help_text=None, verbose_name=' فعال ')),
                ('is_staff', models.BooleanField(default=False, help_text=None, verbose_name=' موظف  ')),
                ('date_joined', models.DateTimeField(auto_now=True, help_text=None)),
                ('gender', models.CharField(choices=[('female', 'انثى '), ('male', 'ذكر ')], default='male', max_length=120)),
                ('has_mark', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('is_developer', models.BooleanField(default=False)),
                ('policy', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'المستخدمين ',
                'db_table': 'account',
            },
        ),
    ]
