# Generated by Django 4.1.7 on 2023-04-12 00:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=200)),
                ('fundationID', models.CharField(max_length=150, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FundationStaffAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor-teacher', ' مدرس - دكتور '), ('lecturer', 'محاضر'), ('students-ffairs', 'مدير شؤون الطلبة')], max_length=50)),
                ('phoneNumber', models.CharField(max_length=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundationStaff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
