# Generated by Django 4.1.7 on 2023-04-12 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.JSONField(default={})),
                ('privace', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=30)),
                ('shares', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userSummaries', to=settings.AUTH_USER_MODEL)),
                ('collabs', models.ManyToManyField(related_name='user_collabs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('summary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summaryTimline', to='summary.summary')),
            ],
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('eventRelated', models.CharField(choices=[('COMMENT', 'Comment'), ('SUMMARY', 'Summary')], max_length=10)),
                ('eventMethod', models.CharField(choices=[('C_ADD', 'Add'), ('C_EDIT', 'Edit'), ('C_DELETE', 'Delete'), ('S_ADD', 'Add'), ('S_EDIT', 'Edit'), ('S_DELETE', 'Delete')], max_length=10)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timelineEvents', to='summary.summarytimeline')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SummaryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaryComments', to='summary.summary')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userComments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentReply', to='summary.summarycomment')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.summary')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
