# Generated by Django 4.1.7 on 2023-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0002_summary_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summarytimeline',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='summarytimeline',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='eventMethod',
            field=models.CharField(choices=[('C_ADD', 'Add Comment'), ('C_EDIT', 'Edit Comment'), ('C_DELETE', 'Delete Comment'), ('S_ADD', 'Add Summary'), ('S_EDIT', 'Edit Summary'), ('S_DELETE', 'Delete Summary'), ('R_ADD', 'Add Reply'), ('R_EDIT', 'Edit Reply'), ('R_DELETE', 'Delete Reply')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='eventRelated',
            field=models.CharField(choices=[('COMMENT', 'Comment'), ('SUMMARY', 'Summary'), ('REPLY', 'Reply')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
