# Generated by Django 4.1.7 on 2023-04-16 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0004_remove_summary_author_summary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_comments_replies', to='summary.summarycomment'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summarycomment',
            name='summary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summray_comments', to='summary.summary'),
        ),
        migrations.AlterField(
            model_name='summarycomment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_summaries_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='summarytimeline',
            name='summary',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_timeline', to='summary.summary'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summary_timeline_events', to='summary.summarytimeline'),
        ),
    ]
